name: CI

on: [push, pull_request]

jobs:
  Build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            build/gradle-jvm
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Build-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}
      - run: ./gradlew :buildPlugin --no-daemon
      - uses: actions/upload-artifact@v3
        with:
          path: output/${{ github.event.repository.name }}.9999.0.0.nupkg
          name: ${{ github.event.repository.name }}.CI.${{ github.run_number }}.nupkg
      - uses: actions/upload-artifact@v3
        with:
          path: output/${{ github.event.repository.name }}-9999.0.0.zip
          name: ${{ github.event.repository.name }}-CI.${{ github.run_number }}.zip
      - uses: actions/upload-artifact@v3
        with:
          path: output
          name: output
  Test:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: |
            build/gradle-jvm
            packages
            ~/.nuget/packages
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-Test-${{ hashFiles('gradlew.bat', 'src/dotnet/*/*.csproj', 'src/dotnet/*.props', 'gradle-wrapper.properties') }}
      - run: ./gradlew :testDotNet --no-daemon
